name: Generate Snake

on:
  schedule: # Runs at midnight daily
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual run

permissions:
  contents: write   # ✅ allow pushing to branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kavya020805
          outputs: dist/snake.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
